version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/build
    overwrite: yes

permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 180
      runas: ubuntu
      env:
        DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PASSWORD:  ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_TIMEZONE:  ${{ secrets.DATABASE_TIMEZONE }}
        DATABASE_USER_NAME: ${{ secrets.DATABASE_USER_NAME }}
        DATABASE_DIALECT: ${{ secrets.DATABASE_DIALECT }}
