# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
    
    	# 윈도우 환경과 리눅스 환경에서 충돌 회피를 위한 package-lock.json 삭제
      - name: delete package-lock.json
        run: rm package-lock.json

      - name: Install dependencies
        run: npm install

      - name: bulid file
        run: npm run build

	# secret 폴더 생성후 .env파일 생성
        # 폴더를 생성하지 않으면 .env 파일이 .gitignore에 의해 무시당해서 안생긴다.
      - name: Create env file
        run: |
          mkdir secret
          cd secret
          touch .env.development
          cat << EOF >> .env.development
          ${{ secrets.ENV }}
          EOF
          cd ../
          
	# tar파일 생성
      - name: Make tar file
        run: tar -cpvzf ./$GITHUB_SHA.tgz *
        shell: bash

      - name: zip distributions
        run: zip -r together-zip.zip ./client/dist ./server ./appspec.yml ./scripts

      - name: AWS configure credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: upload to S3
        run: aws s3 cp --region ap-northeast-2 ./together-zip.zip s3://together-zip/public/

      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name zip-codedeploy
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name zip-codedeploy
          --s3-location bucket=together-zip,bundleType=zip,key=public/together-zip.zip
